name:          Code Guide by @serge_el
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://dg-code-guide.david-goliath.com

markdown:      rdiscount
permalink:     pretty
highlighter:   rouge
